name: runtime_native_named_locks
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  platform: ^3.1.4
  ffi: ^2.1.2
  windows_foundation: ^0.2.0
  win32: ^5.3.0
  native_synchronization: ^0.2.0
  path: ^1.9.0
  stdlibc: ^0.1.4
  meta: ^1.12.0


dev_dependencies:
  test: ^1.25.2
